### ISSUE TITLE
Loop a variable number of times? (while loop)

### ISSUE THREAD

**Issue by SilverWingedSeraph** [gabordemooij/citrine#11]
Is there/are there plans for a while-like loop? E.g., 

```
(condition) whileTrue: {\
    # Do work
}.
```

**Comment by janus** [comment]
@SilverWingedSeraph 

I will set up my system in few days time and I will try out adding it. But from what I have seen all you need is to hookup whileTrue method on Boolean object (Truthy), and process the block. There may be need to use recursive call(crude way).

**Comment by gabordemooij** [comment]
To craft a while loop, send a message whileTrue to a block and attach another block as its parameter

**Comment by gabordemooij** [comment]
```
a := 0.
{\ a inc: 1. ^(a < 5). } whileTrue: {\ Pen write: 'iteration' }.
```
