### ISSUE TITLE
ctr_object* ctr_string_html_escape

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#12]
I looked at the above function and I started thinking that calling **realloc** when we have not exhausted memory block already created by calling **malloc** is not efficient in time . I think this algorithm should be made to be a bit faster by either calling **realloc ** after we have exhausted the memory block already created by **malloc** or while mallocing set the required memory size to be more than the actual string length to start with. If this view is accepted I will send a patch thereafter.
Finally, after calling **malloc**  I would expect that we should check if there is enough memory or not before proceeding. This is lacking.

**Comment by gabordemooij** [comment]
This function needs some work for sure, memory management will be improved overall though (milestone 5)

**Comment by gabordemooij** [comment]
Pull requests are welcome :)

**Comment by gabordemooij** [comment]
applied your PR thanks!
