### ISSUE TITLE
sockets plugin causing fatal errors in such as `malloc()`

### ISSUE THREAD

**Issue by SilverWingedSeraph** [gabordemooij/citrine#13]
I'm working on a sockets plugin, and I'm wondering how I should handle fatal errors such as malloc() failing. Is there a call I can make that will let Citrine shut down cleanly?

**Comment by gabordemooij** [comment]
Just raise an exception:

    CtrStdError = ctr_build_string_from_cstring("Unable to open socket\0");

and then return..., this will cause the Tree Walker to follow the error procedure.

**Comment by gabordemooij** [comment]
http://websocketd.com/ kind of cool, we can make straming web apps.

**Comment by SilverWingedSeraph** [comment]
Forgot to close this, oops.

**Comment by gabordemooij** [comment]
no problem, still experimenting with the websockets?

**Comment by SilverWingedSeraph** [comment]
Haven't been very active because I've been recovering from surgery, but I'm hoping to get back into the thick of it soon.

**Comment by gabordemooij** [comment]
Ai! That sounds severe, hope you get well soon!
