### ISSUE TITLE
`ctr_build_string function` needs some works for test 48

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#15]
I checked that function and I started wondering why it does not free the argument string after memcpy. This looks strange and I tried to free , I got error while on test 48. I am still a bit confuse while C string after converting it to citrine object would still be active and live in subsequent code. And I am not able to figure out much from test 48, please explain it a bit for me.

**Comment by janus** [comment]
Wow.. now I understood the error message I was getting.

You have a few errors:

    You're trying to free memory that's not heap memory. Don't do that.

    You're trying to free the inside of a block of memory. When you have in fact allocated a block of memory, you can only free it from the pointer returned by malloc. That is to say, only from the beginning of the block. You can't free a portion of the block from the inside.

http://stackoverflow.com/questions/20297524/c-free-invalid-pointer

**Comment by gabordemooij** [comment]
Yes this needs some work.

**Comment by janus** [comment]
I just tried something after meditating a way over this issue. I found that ctr_build_string accepts strings on the heap and stack, and that is why it trigged free invalid pointer error. So, this is what I did and it passed test cases. I found every function inside base.c file that calls ctr_build_string and for anyone that has string on the heap I added the below:

ctr_object* result;
result = return ctr_build_string(dest, nlent);
free(dest);
return result;

Please go through and comment. I tend to spend more time studying and assimilating citrine source code. And

**Comment by gabordemooij** [comment]
maybe a macro would be better for this?

**Comment by gabordemooij** [comment]
I think this issue is no longer relevant, most/all memory issues in String, File, Map and Array have been fixed. I only need to test Nil, Object, Boolean, Number, Blocks and the system library but these are low risk and easy to test.
