### ISSUE TITLE
Segfault when using -c option with no input file

### ISSUE THREAD

**Issue by SilverWingedSeraph** [gabordemooij/citrine#2]
For example, if someone were to accidentally do

    ctr -c source.ctr

instead of providing the output and then the input file (not that I did this or anything...), ctr will segfault.

Core dump attached.
[_usr_bin_ctr.1000.crash.zip](https://github.com/gabordemooij/citrine/files/104525/_usr_bin_ctr.1000.crash.zip)

**Comment by gabordemooij** [comment]
Ah, sloppy! thanks for reporting!

**Comment by gabordemooij** [comment]
Seems fixed now?
