### ISSUE TITLE
cgi exists already?

### ISSUE THREAD

**Issue by shinriyo** [gabordemooij/citrine#22]
I read document how to write template like PHP.
But, I couldn't find how to run server.
So, cgi function does not exist yet?

**Comment by SilverWingedSeraph** [comment]
Since Citrine is interpreted, you can use it with any webserver (Apache, Nginx). Just mark your script executable, put the shebang at the top, and set up CGI for your form or page.

**Comment by shinriyo** [comment]
Thank you for replying.
I'll try shebang

**Comment by takano32** [comment]
@gabordemooij Would you close this issue?

**Comment by gabordemooij** [comment]
For now it's CGI only, however we'll have support for SCGI very very soon (because it happens to be already in ccgilib), and then FastCGI (if anyone wants to work on the this please let me know)

https://en.wikipedia.org/wiki/Simple_Common_Gateway_Interface
