### ISSUE TITLE
Removed redundant object

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#27]
It seems to me that variable argument2 is redundant.
ctr_object* ctr_string_skip(ctr_object* myself, ctr_argument* argumentList) {
	ctr_argument* argument1;
	/* ctr_argument* argument2; */
	if (myself->value.svalue->vlen < argumentList->object->value.nvalue) return ctr_build_string("",0);
	argument1 = CTR_CREATE_ARGUMENT();
	/*argument2 = CTR_CREATE_ARGUMENT(); */
	argument1->object = argumentList->object;
	/*argument1->next = argument2; */
	/*argument2->object */
	argument1->next->object = ctr_build_number_from_float(myself->value.svalue->vlen - argumentList->object->value.nvalue);
	return ctr_string_from_length(myself, argument1);
}

**Comment by gabordemooij** [comment]
Looking forward to PR

**Comment by gabordemooij** [comment]
No it needs 2nd argument, cause other function takes 2.
