### ISSUE TITLE
ctr_build_number_from_string

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#28]
What it the reason for using 40 instead of length.
ctr_object* ctr_build_number_from_string(char* str, ctr_size length) {
	char* numCStr;
	ctr_object* numberObject = ctr_internal_create_object(CTR_OBJECT_TYPE_OTNUMBER);
	/* turn string into a C-string before feeding it to atof */
	numCStr = (char*) calloc(40, sizeof(char));
	memcpy(numCStr, str, length);
	numberObject->value.nvalue =  atof(numCStr);
	numberObject->link = CtrStdNumber;
	free(numCStr);
	return numberObject;
}

**Comment by gabordemooij** [comment]
Legacy, please improve if you like.

**Comment by takano32** [comment]
Re-opened in https://github.com/gabordemooij/citrine/issues/43 and close this issue.
