### ISSUE TITLE
ctr_build_string_from_cstring

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#29]
I noticed sentinel '\0' in some places .... Are they not redundant? 
ctr_build_string_from_cstring("Boolean\0");
ctr_build_string_from_cstring("Expected on: argument to be of type string.")

**Comment by gabordemooij** [comment]
Yes, I believe C-compilers will automatically append the NULL byte to literals so these are redundant and can be removed.

**Comment by janus** [comment]
Thanks~
