### ISSUE TITLE
Calling ctr_dparse_parse functions almost back to back

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#3]
I just noticed this statement "program = ctr_dparse_parse(prg);" used two times... within a block and the first call's result not used. Any reason for this?
int main(int argc, char* argv[]) {
	char* prg;
	ctr_tnode* program;
	ctr_argc = argc;
	ctr_argv = argv;
	ctr_malloc_chunk_pointer = 0;
	ctr_mode_compile = 0;
	ctr_mode_load = 0;
	ctr_cli_read_args(argc, argv);
	if (ctr_mode_compile) {
		prg = ctr_internal_readf(ctr_mode_input_file);
		ctr_malloc_mode = 0;
		ctr_malloc_measured_size_addressbook = sizeof(ctr_ast_header);/* adds up to normal addressbook size */
		program = ctr_dparse_parse(prg);
		program = NULL;
		ctr_malloc_mode = 1;
		ctr_malloc_chunk_pointer = 0;
		ctr_malloc_chunk = 0;
		program = ctr_dparse_parse(prg);
		ctr_serializer_serialize(program);
		free(ctr_malloc_chunk);
		free(prg);
		exit(0);
	}

**Comment by SilverWingedSeraph** [comment]
Well, when I remove that statement, the tests fail: 

```
rm -rf *.o ctr
gcc -c -mtune=native siphash.c -Wall -o siphash.o
gcc -c -pedantic-errors -mtune=native utf8.c -Wall -o utf8.o
gcc -c -pedantic-errors -mtune=native memory.c -Wall -o memory.o
gcc -c -pedantic-errors -mtune=native util.c -Wall -o util.o
gcc -c -pedantic-errors -mtune=native base.c -Wall -o base.o
gcc -c -pedantic-errors -mtune=native collections.c -Wall -o collections.o
gcc -c -pedantic-errors -mtune=native file.c -Wall -o file.o
gcc -c -pedantic-errors -mtune=native system.c -Wall -o system.o
gcc -c -pedantic-errors -mtune=native world.c -Wall -o world.o
gcc -c -pedantic-errors -mtune=native lexer.c -Wall -o lexer.o
gcc -c -pedantic-errors -mtune=native parser.c -Wall -o parser.o
gcc -c -pedantic-errors -mtune=native walker.c -Wall -o walker.o
gcc -c -pedantic-errors -mtune=native citrine.c -Wall -o citrine.o
gcc siphash.o utf8.o memory.o util.o base.o collections.o file.o system.o world.o lexer.o parser.o walker.o citrine.o -lm -o ctr
tests/test0109.ctr interpret[1]
tests/test0109.ctr compiledFAIL.
EXPECTED:
I am myself.

BUT GOT:
Expected . but got: 99. no memory.
```

And an error is emitted: 

```
*** Error in `./ctr': malloc(): memory corruption: 0x0000000001aa7320 ***
```

So it's clearly doing something. I'm not sure what, though.

**Comment by gabordemooij** [comment]
1st time it measures size of the program, AST has to be in aligned part of memory. This will probably be improved when reaching milestone 5: memory management. But you're free to start if you like :)
