### ISSUE TITLE
test119

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#30]
Noticed this error while running nightly. Looks like the last test119 is having issue with my versio

EXPECTED:
search=table&restaurant=pizzaria&menu=spaghetti&menu=macaroni&course[main]=canneloni&course[dessert]=tiramisu I was looking for a free table in a pizzaria, but the waiter told me all tables have been corrupted by spaghetti, macaroni and canneloni code.

BUT GOT:
search=table&restaurant=pizzaria&menu=spaghetti&menu=macaroni&course[main]=canneloni&course[dessert]=tiramisu Error, key not found: [Request].

**Comment by gabordemooij** [comment]
Working on this...

**Comment by gabordemooij** [comment]
Seems to be a git issue

**Comment by gabordemooij** [comment]
fixed
