### ISSUE TITLE
[Proposal] String Interpolation

### ISSUE THREAD

**Issue by gosukiwi** [gabordemooij/citrine#32]
String interpolation is an awesome feature a lot of morden languages implement. I really enjoy using it and I think it makes code easier to read. Basically, it looks like this:

```
Pen write: 'Welcome #{name}'.
```

The syntax shown above is Ruby's, ES6 uses a slightly different style:

```
Pen write: 'Welcome ${name}'.
```

Syntax is debatable of course, my question is whether it should be implemented. Yay or nay?

**Comment by gabordemooij** [comment]
I'd rather like to solve this without introducing specific syntax, maybe somthing like:

    s := 100.
    p := 2.
    Pen write: 'Player {p} scored: {s} points!' fill.

**Comment by gosukiwi** [comment]
I like that syntax too. It should be escapable, of course:

    Pen write: 'Mustache is a template engine which uses \{\{\}\} a lot'

Because using `{}` inside a string is quite uncommon, I think it's quite a good syntax for string interpolation.

**Comment by gabordemooij** [comment]
We dont need escaping. Normal strings wont be affected.
Only after sending the unary message 'fill' or something to a String Object the contents of the string will be parsed (dynamically!).

**Comment by gosukiwi** [comment]
Ah, I see! Something like C#'s format. I missed the `fill` :-P

**Comment by gabordemooij** [comment]
Because we use a message there is no need for new syntax. But it also means we may use a bit more freedom when choosing our template slots (after all they are not processed by default), for instance 'Player p score s points' may work as well (single char detection - why not?).

**Comment by gosukiwi** [comment]
Yeah, but I like using some kind of syntax, that way you know at a glance whether a string has some values interpolated, otherwise, it can be hard to see. Also, editors normally highlight interpolated things with a different color.

**Comment by gabordemooij** [comment]
Yes, you're right, so what shall we do?

- #{ruby}
- ${Javascript}
- $php
- {$php}
- %c
- :sql

What other styles do we have?

**Comment by janus** [comment]
I will go for #{ruby} ...

**Comment by gosukiwi** [comment]
Uhm, well, because Citrine's syntax uses brackets a lot, maybe something with brackets would be intuitive, something simple like `{foo}`. On the other hand, it might be confusing: 

    { name | Pen write: 'Hello {name}' } applyTo: 'mike'

Maybe something like SQL would be cleaner

    { name | Pen write: 'Hello :name' } applyTo: 'mike'

**Comment by gabordemooij** [comment]
We'll since its trivial to implement we can experiment with different kinds of slots, who likes to take a shot at this?

**Comment by janus** [comment]
Great!       Let me be the judge :)

**Comment by gabordemooij** [comment]
Hey Janus, Takano, I just added String interpolation

https://github.com/gabordemooij/citrine/commit/8781d1d434dea2aff9b9da08889ac43950e28109

current format is: {%x}

```
x := 'World'.
Pen write: 'Hello {%x}'.
```

However we can still change this, any suggestions (mechanism is quite generic so... ) ?

**Comment by janus** [comment]
Great! ... I will check it out..

**Comment by takano32** [comment]
I think `{%x}` is Smalltalk-ish, it is very good.
But it doesn't have such as `printf(3)` usability aspect of format.

I like Python style String interpolation that's also ported to Ruby.

in Python

```python
a = 'hello'
b = 'world'
print('%s %s' % (a,b))
```

in Ruby

```ruby
a = 'hello'
b = 'world'
puts '%s %s' % [a, b]
```

And below type is more generic in Citrine I think.

```
a := 'hello'.
b := 'world'.
x := '%s %s' format: #(a b)
Pen write: y.
```

But this can cause noisy, wide long code.

```
x := 'World'.
Pen write: ('Hello %s' format: #(x)).
```

Hmmm... String interpolation is difficult for me...

**Comment by gabordemooij** [comment]
I propose $$ :

1. less verbose to type than the concat $$x is easier than ' + x + '... or {%x} or #{x}
2. dont have to escape a single $ (annoying) neither do we need two types of quotes (' ") as in PHP
3. very fast to type: double tab a $
4. easy to read/spot $$x in a string
5. familiar (not too strange) the $ is used in PHP and JSTL/Perl/Java/Basic
