### ISSUE TITLE
citrine-lang.org landing page

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#34]
Won't it be nice to show the user how to run the program. Something like "$ ctr hello.ctr" 
A slightly over-engineered 'hello world' program:

Butler := Object new.
Butler on: 'greet:' do: { name |
	Pen write: 'Welcome ' + name.
}.
james := Butler new.
james greet: 'visitor'.

This program will generate the following output:
Welcome visitor

**Comment by gabordemooij** [comment]
done
