### ISSUE TITLE
mk bash and make install

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#35]
I can't truly figure out the difference between ./mk.bash and make install except cp ./ctr /usr/bin/ctr and object files littering folder. Is there something I am missing?

git clone --depth=50 https://github.com/gabordemooij/citrine.git gabordemooij/citrine
cd gabordemooij/citrine
git fetch origin
git checkout -qf FETCH_HEAD
./mk.bash
make install

**Comment by gabordemooij** [comment]
mk.bash uses different make files across platforms. The main catch is that Linux needs the -ldl compiler option to make program symbols of Citrine accessible to plugins. OpenBSD doesnt need this option (and will complain if I add it).
