### ISSUE TITLE
Citrine's Website on GitHub

### ISSUE THREAD

**Issue by gosukiwi** [gabordemooij/citrine#36]
It would be great to have Citrine's website source code on GitHub so anyone can collaborate :)

**Comment by gabordemooij** [comment]
You can already edit the website by modifying the source :)

The most important page of the website is the docs page, this page is generated from the UNIX manual file (distributed along with source code) and this UNIX manual file is generated by sman.ctr, a script that inspects the source tree. So if you want to improve the docs page(s) you can simply change the source code comments - those will automatically update the online manual.

As for the remaining 3 pages (website is only 4 pages total) I accept change requests but I'd prefer to maintain these manually. However I plan to make parts of these pages accessible through the source code as well.

**Comment by gosukiwi** [comment]
Oh I see! What about changing the template though? :) Will that be accessible?

**Comment by gabordemooij** [comment]
I added the CSS file to the misc folder, so you can change the style of the man pages online.
The rest of the template is actually generated by man itself (exports to html), feel free to do whatever you like. You can tweak sman, add another citrine template script or whatever... feel creative,  have fun :)

**Comment by gosukiwi** [comment]
Awesome, thanks! I don't think I'll tweak it immediatly but when I get some
free weekend, I'll play with it.

**Comment by takano32** [comment]
This issued may be solved by:

- [cggi-1.2](https://github.com/gabordemooij/citrine/tree/4940420001c79bff89c93e8598ec0d47ee6a803b/plugins/request/ccgi-1.2)

- [ctrstyle.css](https://github.com/gabordemooij/citrine/blob/4940420001c79bff89c93e8598ec0d47ee6a803b/misc/ctrstyle.css)

I'll close this issue with this comment.
