### ISSUE TITLE
n times: not working

### ISSUE THREAD

**Issue by SilverWingedSeraph** [gabordemooij/citrine#4]
I have a program

    3 times: {\ Pen write: 'Test.'.}.

Which, when run with the ctr, produces no output. Am I doing something wrong, or is the times: functionality not implemented yet?

**Comment by SilverWingedSeraph** [comment]
Well, I appear to have made a dumb error. * is currently the notation for for loops. Closed.

**Comment by gabordemooij** [comment]
I will re-add times: later, I think 'times' is more readable anyway. I think I keep both '*' for those who prefer a short notation and 'times:' for better readability. What do you think?

**Comment by SilverWingedSeraph** [comment]
I think having both available is definitely a good idea.

**Comment by gabordemooij** [comment]
implemented!

**Comment by SilverWingedSeraph** [comment]
Thanks!
