### ISSUE TITLE
Error message in example code

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#44]
The below example from citrine web omitted " ' " before world!

Pen write: 'Hello', write: world!'.

**Comment by takano32** [comment]
I tried run the code.

`Pen write: 'Hello', write: world!'.`

```
$ cat 44.ctr
Pen write: 'Hello', write: world!'.
$ ../ctr 44.ctr
Error, unexpected token: 9.
```

I think the example should be

```
Pen write: 'Hello', write: ' ', write: 'world!'.
```


```
$ cat 44.ctr
Pen write: 'Hello', write: ' ', write: 'world!'.
$ ../ctr 44.ctr
Hello world!
```

**Comment by gabordemooij** [comment]
Fixed, quite a crucial example to contain such a mistake... oops ;)
