### ISSUE TITLE
Citrine gammar

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#45]
I am drive to understand citrine parser, I reproduced the grammar. However, I missed out a couple of things like block does not have parameters(someone here should help me figure this out). And I would like to hear your view and comments.

```
program ::-> statement dot {statement}
statement ::-> expression| return_token return | end
end ::-> endofprogram
return ::-> expression
expression ::-> receiver re_object
re_object ::->  assignment_token assignment| messages
assignment ::->  expression
receiver ::->  nil |  true |  false | number | string | ref | block | popen
ref ::-> [my_ref | var_ref ] name
block ::-> "{" { ref } "|" block_main "." "}" 
block_main ::-> return_token expression | expression
popen ::-> expression ")"
messages ::->  [REF | CHAIN ] message messages | empty
message ::->  bin expression | colon expression {expression} | unary_message
unary_message ::-> name
nil ::-> nil_object
true ::-> true_object
false ::-> false_object
string ::-> string_object
number ::-> number_object
block ::-> block_object
my_ref ::-> "my" 
var_ref ::-> "var" 
popen ::-> "(" expression ")"
assignment_token ::-> ":="
return_token ::-> "^"
bin ::-> "+"|"-"|"/"|"*"|"<"|">"|"=" 
colon ::-> ":"
dot ::-> "."
name ::-> [A-Za-z][A-Za-z]*
```

**Comment by gabordemooij** [comment]
a block without a parameter is:

    {\ ...block... }

**Comment by janus** [comment]
@gabordemooij 

Please go through and point out what needs to be changed, I intend to add this file to my cloned repo so that it would be easier for anyone to study the language.  
I have changed "messages ::->  [REF | CHAIN ] message messages | empty" to "messages ::->  [ref | chain ] message messages | empty"
chain ::->  ","

**Comment by takano32** [comment]
This issue relates to #60 .

**Comment by gabordemooij** [comment]
I'll try but I find these grammars somewhat hard to read. Did you cover these cases:

1. All messages of exactly symbol (+ - / but also 'a', implementation: 1 symbol == 1 unicode code point) are binary messages taking 2 arguments without the need for a colon (can a grammar capture a rule like this?)
2. The comma, used to chain keyword messages (nothing else) for example: (a > b) ifTrue: {\...}**,** else:
3. The 'titled pipe' {\ used to denote a block without parameters
4. The 'me' reference, same as 'my' but for messages instead of properties
5. the backtick ` though this not part of the lexer, prefixing a message to yourself with a backtick causes invocation of the overridden parent method

**Comment by gabordemooij** [comment]
bin message is not limited to 

    bin ::-> "+"|"-"|"/"|"*"|"<"|">"|"=" 

see point 1, this is where Citrine differs from Smalltalk, you can any 'symbol' as a binary message.

**Comment by gabordemooij** [comment]
popen cannot be a receiver

     receiver ::->  nil |  true |  false | number | string | ref | block | popen

**Comment by gabordemooij** [comment]
empty?

    messages ::->  [REF | CHAIN ] message messages | empty

**Comment by gabordemooij** [comment]
var is only needed if NOT in global scope, it's mandatory in non-global scope. In global scope, it's optional.

    var_ref ::-> "var"

**Comment by gabordemooij** [comment]
This is not true:

    name ::-> [A-Za-z][A-Za-z]*

a name may use any character you want, there are no restrictions except tokens and the 'special' binary messages: < > = + / * - >= <=  this has been done to allow  cases like (3-a), see no space, however Citrine offers more freedom for names, you may literally use any symbol except for tokens and this limited set of characters. A binary message may be an emojicon like a pile of poo.

**Comment by janus** [comment]
Thanks for comments, I  am still studying this great language. I have not really read the language syntax beyond what I gleaned from C lang code base. I will be spend a couple of days to dive into this language.

I used the below to infer that popen is a receiver ... Looks like I am pretty wrong.
ctr_tnode* ctr_cparse_receiver() {
	int t;
	if (ctr_mode_debug) printf("Parsing receiver.\n");
	t = ctr_clex_tok();
	ctr_clex_putback();
	switch(t){
		case CTR_TOKEN_NIL:
			return ctr_cparse_nil();
		case CTR_TOKEN_BOOLEANYES:
			return ctr_cparse_true();
		case CTR_TOKEN_BOOLEANNO:
			return ctr_cparse_false();
		case CTR_TOKEN_NUMBER:
			return ctr_cparse_number();
		case CTR_TOKEN_QUOTE:
			return ctr_cparse_string();
		case CTR_TOKEN_REF:
			return ctr_cparse_ref();
		case CTR_TOKEN_BLOCKOPEN:
			return ctr_cparse_block();
		case CTR_TOKEN_PAROPEN:
			return ctr_cparse_popen();

**Comment by janus** [comment]
I could not figure out "titled pipe" from the below code, it looks like it is no more part of the code 
The 'titled pipe' {\ used to denote a block without parameters

ctr_tnode* ctr_cparse_block() {
	ctr_tnode* r;
	ctr_tlistitem* codeBlockPart1;
	ctr_tlistitem* codeBlockPart2;
	ctr_tnode* paramList;
	ctr_tnode* codeList;
	ctr_tlistitem* previousListItem;
	ctr_tlistitem* previousCodeListItem;
	int t;
	int first;
	if (ctr_mode_debug) printf("Parsing code block.\n");
	ctr_clex_tok();
	r = CTR_PARSER_CREATE_NODE();
	r->type = CTR_AST_NODE_CODEBLOCK;
	codeBlockPart1 = CTR_PARSER_CREATE_LISTITEM();
	r->nodes = codeBlockPart1;
	codeBlockPart2 = CTR_PARSER_CREATE_LISTITEM();
	r->nodes->next = codeBlockPart2;
	paramList = CTR_PARSER_CREATE_NODE();
	codeList  = CTR_PARSER_CREATE_NODE();	
	codeBlockPart1->node = paramList;
	codeBlockPart2->node = codeList;
	paramList->type = CTR_AST_NODE_PARAMLIST;
	codeList->type = CTR_AST_NODE_INSTRLIST;
	t = ctr_clex_tok();
	first = 1;
	while(t == CTR_TOKEN_REF) {
		ctr_tlistitem* paramListItem = CTR_PARSER_CREATE_LISTITEM();
		ctr_tnode* paramItem = CTR_PARSER_CREATE_NODE();
		long l = ctr_clex_tok_value_length();
		paramItem->value = ctr_malloc(sizeof(char) * l, 0);
		memcpy(paramItem->value, ctr_clex_tok_value(), l);
		paramItem->vlen = l;
		paramListItem->node = paramItem;
		if (first) {
			paramList->nodes = paramListItem;
			previousListItem = paramListItem;
			first = 0;
		} else {
			previousListItem->next = paramListItem;
			previousListItem = paramListItem;
		}
		t = ctr_clex_tok();
	}
	if (t != CTR_TOKEN_BLOCKPIPE) {
		printf("Error expected blockpipe.");
		exit(1);
	}
	t = ctr_clex_tok();
	first = 1;
	while((first || t == CTR_TOKEN_DOT)) {
		ctr_tlistitem* codeListItem;
		ctr_tnode* codeNode;
		if (first) {
			if (ctr_mode_debug) printf("First, so put back\n");
			ctr_clex_putback();
		}
		t = ctr_clex_tok();
		if (t == CTR_TOKEN_BLOCKCLOSE) break;
		ctr_clex_putback();
		codeListItem = CTR_PARSER_CREATE_LISTITEM();
		codeNode = CTR_PARSER_CREATE_NODE();
		if (ctr_mode_debug) printf("--------> %d %s \n", t, ctr_clex_tok_value());
		if (t == CTR_TOKEN_RET) {
			codeNode = ctr_cparse_ret();
		} else {
			codeNode = ctr_cparse_expr(0);
		}
		codeListItem->node = codeNode;
		if (first) {
			codeList->nodes = codeListItem;
			previousCodeListItem = codeListItem;
			first = 0;
		} else {
			previousCodeListItem->next = codeListItem;
			previousCodeListItem = codeListItem;
		}
		t = ctr_clex_tok();
		if (t != CTR_TOKEN_DOT) {
			printf("Expected . but got: %d.\n", t);
			exit(1);
		}
	}
	return r;
}

**Comment by gabordemooij** [comment]
Tilted pipe is actually not enforced, you're currently allowed to use them both, the convention for now is to use \ for no params only.


     if (c == '|' || c == '\\') { ctr_code++; return CTR_TOKEN_BLOCKPIPE; }

This will change at some point however, the pipe rules will be enforced eventually.

Also not that I am still tweaking some parts of the language, there are no more || and &&, you'll have to use or: and and: instead, this has been done to reduce the number of 'special' tokens and increase readability for non-programmers.
