### ISSUE TITLE
So cleaning needed

### ISSUE THREAD

**Issue by janus** [gabordemooij/citrine#5]
@gabordemooij 

Thanks for this great source code, I was able to get the basic idea. It is cleanly written and in a natural way. However,   the code below looks great but I was thinking that it would be great to fail fast by having the IF statement before memcpy function.

void ctr_serializer_serialize(ctr_tnode* t) {
	FILE *f;
	f = fopen(ctr_mode_compile_save_as,"wb");
	memcpy( ctr_malloc_chunk, ctr_default_header, sizeof(ctr_ast_header));/* append to addressbook, new header */
	if (!f) { printf("Unable to open file!"); exit(1); }
	fwrite(ctr_malloc_chunk, sizeof(char), ctr_malloc_measured_size_code+ctr_malloc_measured_size_addressbook, f);
	fclose(f);
}

**Comment by gabordemooij** [comment]
Fixed thru merge I guess, feel free to send any more clean-ups!
