### ISSUE TITLE
Enforce pipe rules

### ISSUE THREAD

**Issue by gabordemooij** [gabordemooij/citrine#62]
Right now you may use \ and | to separate params in a block from the block body.
The Lexer should enforce use of \ only for blocks without any parameters and forbid the use of | for empty param sections.

**Comment by MadcapJake** [comment]
Why use two characters for this at all? Why not converge on using one for both situations?

**Comment by gabordemooij** [comment]
Well mostly because it does not look very nice, but that's basically all. Maybe this is not a real issue at all...

**Comment by gabordemooij** [comment]
The pipe has been discontinued, we now use smalltalk like parameters ( :param1 :param2 )
