### ISSUE TITLE
Socket functionality

### ISSUE THREAD

**Issue by SilverWingedSeraph** [gabordemooij/citrine#8]
Should socket functionality be implemented in the language, since POSIX allow it to work in basically the same way across UNIX systems, or should it be a plugin? If it should be built in, could I have some pointers on how to create new built in objects? Thanks.

**Comment by gabordemooij** [comment]
These will be plugins.

I have yet to create a plugin loader, but it's the first thing on my list (after cleaning up and releasing 0.3).

For now, to make a build-in object:

1. Add the object to citrine.h, use ctr_object*
2. Add the object to the world in world.c
3. Add a method using name convention: ctr_myobject_mymethod(myself, arguments)
4. Add the method to the world, pass a reference &ctr_myobject_mymethod

Easy examples are:
* Pen write
* String ltrim

**Comment by SilverWingedSeraph** [comment]
Thanks! I had somehow missed the mechanism for initial population in `world.c`. I'll work on the functionality in my own fork and then move it to a plugin when that's implemented.
