### ISSUE TITLE
Small memory leak in ctr_internal_plugin_find

### ISSUE THREAD

**Issue by twiggler** [gabordemooij/citrine#91]
The buffer `realPathModName` as allocated by `realpath` is never freed (see [here](https://github.com/gabordemooij/citrine/blob/746331e4df2f65d6d4a8fa59b6ec1c8ccddde9ac/util.c#L122))

Do you want to wait and let me fix it on my branch (it will probably take a while before that one is ready to be merged), or do you want to fix it yourself?

**Comment by gabordemooij** [comment]
I will address this asap!
