### ISSUE TITLE
Recipe for target 'install' failed

### ISSUE THREAD

**Issue by Fendse** [gabordemooij/citrine#93]
When attempting to run `make install` when setting up citrine, it fails after attempting the `cp ./ctr /usr/bin/ctr` step, due to `cp` failing with the message `cp: cannot stat './ctr': No such file or directory`.

It *does* successfully create the binaries in the respective `bin/"$OS"` folder, so it's not a *major* issue, but still.

I'm running the command from the repository's root folder (the one containing the makefile), and I'm running Ubuntu 18.04 through WSL on Windows 10 - `$OS` and `$ISO` are unset by default, so I've tried running with those manually set to various values and successfully built for all combinations of (Linux/OpenBSD) and (us/nl/ro) I've tried, apart from that final `cp` step which always fails (even when running as root).

**Comment by gabordemooij** [comment]
Hi,

I see there are some minor issues with the scripts.
Have you tried the mk.sh script?
It builds Citrine for all the available languages and sets the $OS and $ISO variables accordingly.
I will look into this and improve the scripts.

As a matter of fact, to make the building process easier, I am also removing the reliance on the bsd library, some users have difficulty installing this? Do you encounter issues with lib-bsd?

**Comment by Fendse** [comment]
Hi,

The `mk.sh` script works fine. I didn't notice any library issues, and all builds managed to produce the expected files in the `citrine/bin/$OS` folder - they only failed once make tried to also copy the `ctr` file into `/usr/bin`, as it had already been moved elsewhere and no longer existed where the script expected it to.
